[package]
name = "chartered-db"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1", features = ["sqlite", "r2d2"] }
tokio = { version = "1" }
dotenv = "0.15"
