[package]
name = "chartered-db"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chartered-fs = { path = "../chartered-fs" }

bitflags = "1"
diesel = { version = "1", features = ["sqlite", "r2d2"] }
displaydoc = "0.2"
itertools = "0.10"
thiserror = "1"
tokio = "1"
dotenv = "0.15"
