[package]
name = "test-using-chartered"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
charteredtest = { version = "1", registry = "chartered" }
